### ISSUE TITLE
flagstaff microbiome project broken/missing image

### ISSUE THREAD

**Issue by jairideout** [gregcaporaso/gregcaporaso.github.com#20]
The [Flagstaff Microbiome Project page](http://caporasolab.us/projects/flagstaff-microbiome/) has a broken/missing image.

**Comment by jairideout** [comment]
@ebolyen is there a way to have a profile page without an image? I don't think there's a logo/image for this project.

**Comment by ebolyen** [comment]
@jairideout opened a pull request which fixes this.

**Comment by jairideout** [comment]
Thanks!
