### ISSUE TITLE
some profiles aren't displaying

### ISSUE THREAD

**Issue by jairideout** [gregcaporaso/gregcaporaso.github.com#33]
Some of the profiles (John, Arron, Kestrel, maybe others) aren't displaying on the live website. @ebolyen can you please take a look?

**Comment by ebolyen** [comment]
They just need to be added to the `_config.yml`

**Comment by jairideout** [comment]
Sounds good, do you mind taking care of this and making a note of this step on the README instructions?

**Comment by ebolyen** [comment]
I would prefer not to be responsible for the ordering. Can you give me a
list?

**Comment by jairideout** [comment]
@gregcaporaso and I don't care, I think they were just added in the order that people added their profiles to the website. I'm fine with keeping to that or alphabetical by last name (ascending or descending sort is fine). Just make sure @gregcaporaso is listed first :P

**Comment by jairideout** [comment]
@ebolyen it looks like all profiles are displaying now except for John's. Can you look into this when you have a sec?

**Comment by jairideout** [comment]
Looks like this was fixed, closing. Thanks @ebolyen!
